server:
  port: 8087

spring:
  application:
    name: api-gateway
  security:
    enabled: false
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customers/**
          filters:
          - name: RequestRateLimiter
            args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 1  # Requests per second
                redis-rate-limiter.burstCapacity: 10 # Maximum allowed burst
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
  redis:
    host: localhost
    port: 6379
logging:
  level:
    org.springframework.cloud.gateway.filter.rate-limit: DEBUG
    org.springframework.web: DEBUG

